sudo: required

services:
  - docker

before_install:
  - docker build -t ssengalanto/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ssengalanto/react-test npm test

after_success:
  - docker build -t ssengalanto/multi-client ./client
  - docker build -t ssengalanto/multi-nginx ./nginx
  - docker build -t ssengalanto/multi-server ./server
  - docker build -t ssengalanto/multi-worker ./worker
  # log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take those images and push it to docker hub
  - docker push "$DOCKER_ID"/multi-client
  - docker push "$DOCKER_ID"/multi-nginx
  - docker push "$DOCKER_ID"/multi-server
  - docker push "$DOCKER_ID"/multi-worker